### ISSUE TITLE
Switch to SRV lookups for service endpoints

### ISSUE THREAD

**Issue by jimmidyson** [noctarius/hazelcast-kubernetes-discovery#1]
Currently connections will be made to the service IP rather than the pod IPs. Switching to SRV records will enable discovery of pod IPs & ports from DNS.

I'll submit a PR to see how this looks & what you think.

**Comment by purplefox** [comment]
@noctarius I'd be interested to understand how the current implementation works as it returns the service's IP not the pod IPs.

For forming a cluster between different pods isn't it the pod IPs that need to be discovered?
