### ISSUE TITLE
Please sign the CLA (Contributors License Agreement)

### ISSUE THREAD

**Issue by noctarius** [noctarius/hazelcast-kubernetes-discovery#15]
Hey guys,

We would like to go forward and officially support the kubernetes plugin. That includes moving the plugin repository to the Hazelcast GitHub account and handing over responsibility to our integrations team.

To make this step it would be great if you could help out and sign our Contributors License Agreement to give us full permissions over the contributions you did. I really appreciate your help and time and hope to see more contributions in the future :)

CLA necessary from:
- @jimmidyson *
- @amoAHCP *
- @ReToCode *
- @yurybubnov
- @mrahbar (since I would like to merge your PR as well) *

You can find information as well as the instructions on our public part of the wiki: https://hazelcast.atlassian.net/wiki/display/COM/Hazelcast+Contributor+Agreement

Thanks again and I hope to see further PRs coming along :)

\* already signed

**Comment by ReToCode** [comment]
Glad to hear that :) Sent the form back to you.

**Comment by jimmidyson** [comment]
A paper CLA? Sheesh ;) Will sign it later.

**Comment by noctarius** [comment]
Thanks guys!

**Comment by noctarius** [comment]
@yurybubnov can you please sign the CLA?

You're contribution (even though not connected to your account anymore):
https://github.com/noctarius/hazelcast-kubernetes-discovery/pull/13

with commits:
https://github.com/noctarius/hazelcast-kubernetes-discovery/commit/34455adb98e52708a38eff41037a3dc9b9aa40aa
https://github.com/noctarius/hazelcast-kubernetes-discovery/commit/c1792cdf938bf6797f7a2874f43523e5edd9f3f8

Thanks a lot!

**Comment by noctarius** [comment]
Ok reverted the only missing signed CLA pull request

**Comment by noctarius** [comment]
PS: Thanks to the other guys for signing it :)
