### ISSUE TITLE
Is it neccesary to configure discovery on client side when using a Kubernetes service?

### ISSUE THREAD

**Issue by sebasmoyano** [noctarius/hazelcast-kubernetes-discovery#25]
If clients connect to server through a Kubernetes service, Is it neccesary to configure discovery on client side?

**Comment by noctarius** [comment]
You cannot connect through a kubernetes service, as a Hazelcast client needs to connect to all cluster members not just a single one. There's a dummy client configuration which is ok with "one member" but not sure it'll work over a kubernetes service, never tried it.

That said, it also means clients cannot (are not supported) to run outside the kubernetes environment.

**Comment by sebasmoyano** [comment]
Perfect. Thank you very much for the prompt reply.

**Comment by noctarius** [comment]
You're welcome, gonna close the issue :)
