### ISSUE TITLE
Property names in the README are not correct

### ISSUE THREAD

**Issue by purplefox** [noctarius/hazelcast-kubernetes-discovery#3]
They need to be prefixed with:

`hazelcast.kubernetes.` in order to work

**Comment by noctarius** [comment]
Nope only if passed on command line (using -Dhazelcast.kubernetes...)

**Comment by purplefox** [comment]
I don't know what I am doing wrong, but if I don't prefix the properties with that I get the following:

Caused by: java.lang.RuntimeException: For kubernetes discovery either 'service-dns' or 'service-name' and 'namespace' must be set

Here is the config:

https://gist.github.com/purplefox/21136af37ae7a34677c0

**Comment by noctarius** [comment]
Is this caused by issue #6?

**Comment by purplefox** [comment]
I think so, when I fix 6, this issue seems to go away

**Comment by noctarius** [comment]
perfect, thanks - sorry for the dns issues, haven't really used it yet (why not using the api client version)?

**Comment by jimmidyson** [comment]
On a secured kubernetes (eg openshift) to use the api client version you need to give the service account the pod runs under karma to query the api server. Extra set up steps & seems better to be able to do this without api server to me. SRV records are generally great for cluster discovery.

**Comment by saturnism** [comment]
great point abt using dns record in this case!
