### ISSUE TITLE
Not possible to only provide a service-dns

### ISSUE THREAD

**Issue by purplefox** [noctarius/hazelcast-kubernetes-discovery#6]
According to the README it should be possible to provide only a `service-dns` property when DNS based lookups are required.

However if only this property is provided then it fails to load properties throwing an exception:

https://github.com/noctarius/hazelcast-kubernetes-discovery/blob/hazelcast-kubernetes-discovery-0.9.1/src/main/java/com/noctarius/hazelcast/kubernetes/HazelcastKubernetesDiscoveryStrategy.java#L51

"For kubernetes discovery either 'service-dns' or " + "'service-name' and 'namespace' must be set");
"

To fix, the line should read:

`if (serviceDns == null && (serviceName == null || namespace == null)) {`

**Comment by noctarius** [comment]
ouch -.- beginners mistake and had to give it 3 looks before I saw the difference between yours and mine *back to basics book* ;-)
