### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by jimmidyson** [noctarius/hazelcast-kubernetes-discovery#7]
Any chance of a release please?

**Comment by purplefox** [comment]
Pretty please? ;)

**Comment by noctarius** [comment]
Sorry guys, totally missed that. Just did it:
https://oss.sonatype.org/content/repositories/releases/com/noctarius/discovery/hazelcast-kubernetes-discovery/0.9.2/

Maven central sync is scheduled and will be executed soon.

**Comment by jimmidyson** [comment]
This is released & synced.
