### ISSUE TITLE
Connection failed to Kubernetes when using the service strategy

### ISSUE THREAD

**Issue by cescoffier** [noctarius/hazelcast-kubernetes-discovery#9]
When Kubernetes runs without the DNS support (as it's a plugin), the resolution fails. 

The host is unknown. In this case the URL can be computed as follows: `KUBERNETES_SERVICE_HOST}:${KUBERNETES_SERVICE_PORT}`

See https://github.com/fabric8io/kubernetes-client/issues/35

**Comment by noctarius** [comment]
You can switch to the service discovery based on the kubernetes REST API, which is the preferred way anyways :-)

Just configure servicename and namespace and you'll get non-dns based lookups.

PS: maybe I misunderstood what you're trying to say, feel free to reopen to clarify if the answer doesn't help.
